### ISSUE TITLE
Main project without using story board

### ISSUE THREAD

**Issue by foffux** [hons82/THMoreFromDeveloper#1]
Hello.
I was trying to use your controller but I was not able to since I have to run it not from a story board but programmatically.
So I was wondering if you can also provide an example about running your project without story board. It will be really helpful.
Thank you so much.

**Comment by hons82** [comment]
Hi, 
actually in this case its quite simple. The only thing that you need to google in your case is how to create a [UICollectionViewController without storyboard](http://stackoverflow.com/questions/17856055/creating-a-uicollectionview-programmatically). 
Then this library is just a Cell in such a UICollectionViewController.

~Hannes

**Comment by foffux** [comment]
Hello
Thanks for you answer.
Actually, I already tried and I guess I did everything in right manner. But I could not get app icons downloaded. Actually I could also not see your empty icon and this means something was wrong. But I cannot understand how.
My controller is:

``` objective-C
- (void)viewDidLoad
{
    [super viewDidLoad];

    //Get status bar frame
    CGRect statusBarViewRect = [self.view convertRect:[UIApplication sharedApplication].statusBarFrame fromView:nil];
    CGFloat statusBarHeight = CGRectGetHeight(statusBarViewRect);

    UICollectionViewFlowLayout *flowLayout = [[UICollectionViewFlowLayout alloc] init];
    [flowLayout setScrollDirection:UICollectionViewScrollDirectionVertical];
    flowLayout.minimumInteritemSpacing = kCollectionSpacing;
    _collectionView = [[UICollectionView alloc] initWithFrame:CGRectMake(self.view.bounds.origin.x, statusBarHeight + kYSettingsOffset, self.view.bounds.size.width, self.view.bounds.size.height) collectionViewLayout:flowLayout];
    _collectionView.backgroundColor = [UIColor clearColor];
    _collectionView.delegate = self;
    _collectionView.dataSource = self;
    [_collectionView registerClass:[THMoreFromDeveloperCell class] forCellWithReuseIdentifier:@"MoreFromDeveloperCell"];
    [_collectionView setAllowsMultipleSelection:NO];

    [self drawGradientBackground];

#warning - DeveloperIds needed to retrieve developer's apps; gradient background over collection view background
    //moreFromDeveloperIds = @[@"509943167",@"875251011",@"420636551",@"645859810",@"767319014"];
    moreFromDeveloperIds = @[@"298910979"];
    self.model = [[THMoreFromDeveloperModel alloc] init];
    [[NSNotificationCenter defaultCenter] addObserver: self selector: @selector(appIdsLoaded:) name:kMoreFromDeleveloperDone object:nil];

    Reachability *reach = [Reachability reachabilityWithHostname:@"www.google.com"];
    // Tell the reachability that we want to be reachable on 3G/EDGE/CDMA
    reach.reachableOnWWAN = YES;
    // Here we set up a NSNotification observer. The Reachability that caused the notification
    // is passed in the object parameter
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(reachabilityChanged:)
                                                 name:kReachabilityChangedNotification
                                               object:nil];

    [reach startNotifier];

    [self setupBackButton];

    [self.view addSubview:_collectionView];
}

- (void)setupBackButton
{
    //Info button
    //Build the button
    UIImage *backDefault = [UIImage imageNamed:@"Back_Icon.png"];
    UIImage *backHighligthed = [UIImage imageNamed:@"Back_Icon_Highlighted.png"];
    CGRect frameBackImg = CGRectMake(0.0f, 0.0f, backDefault.size.width, backDefault.size.height);

    UIButton *customBackButton = [UIButton buttonWithType:UIButtonTypeCustom];
    [customBackButton setFrame:frameBackImg];
    [customBackButton setBackgroundImage:backDefault forState:UIControlStateNormal];
    [customBackButton setBackgroundImage:backHighligthed forState:UIControlStateHighlighted];
    [customBackButton addTarget:self action:@selector(backTapped:) forControlEvents:UIControlEventTouchDown];
    [customBackButton setShowsTouchWhenHighlighted:NO];

    UIBarButtonItem *backButton = [[UIBarButtonItem alloc] initWithCustomView:customBackButton];

    self.navigationItem.leftBarButtonItems = @[backButton];
}

- (void)backTapped:(id)sender
{
    [self.navDelegate dismissInfoRelatedVc];
}

- (void)didReceiveMemoryWarning
{
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

#pragma mark - UICollectionViewDataSource

- (NSInteger)collectionView:(UICollectionView *)collectionView numberOfItemsInSection:(NSInteger)section
{
    //return [moreFromDeveloperIds count];
    return [self.model jsonResults] ? [self.model.jsonResults count] : 0;
}

- (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath
{
    THMoreFromDeveloperCell *cell = [collectionView dequeueReusableCellWithReuseIdentifier:@"MoreFromDeveloperCell" forIndexPath:indexPath];
    //[cell setupWithAppId:moreFromDeveloperIds[indexPath.row]];
    [cell setupWithLookUpDictionary:self.model.jsonResults[indexPath.row]];
    return cell;
}

- (CGSize)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout*)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath *)indexPath
{
    return CGSizeMake(kCollectionWidth, kCollectionHeight);
}

- (UIEdgeInsets)collectionView:(UICollectionView*)collectionView layout:(UICollectionViewLayout *)collectionViewLayout insetForSectionAtIndex:(NSInteger)section
{
    return UIEdgeInsetsMake(kCollectionSpacing, kCollectionSpacing, kCollectionSpacing, kCollectionSpacing); //top, left, bottom, right
}

#pragma mark - UICollectionViewDelegate

- (void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath
{
    NSLog(@"cell #%ld was selected", (long)indexPath.row);
    [[UIApplication sharedApplication] openURL:[NSURL URLWithString:self.model.jsonResults[indexPath.row][@"trackViewUrl"]]];
}

#pragma mark - Callback

- (void)appIdsLoaded:(NSNotification*)notification
{
    [_collectionView reloadData];
}

- (void)reachabilityChanged:(NSNotification*)notification
{
    [self.model loadDeveloperId:moreFromDeveloperIds[0]];
}

- (void)dealloc
{
    [[NSNotificationCenter defaultCenter] removeObserver:self name:kReachabilityChangedNotification object:nil];

    NSArray *viewsToRemove = [self.view subviews];
    for (UIView *view in viewsToRemove) {
        [view removeFromSuperview];
    }

    self.model = nil;
}
```

And I simply call it:

```
moreFromDeveloperCollectionViewController = [[RMAMoreFromDeveloperViewController alloc] init];
            moreFromDeveloperCollectionViewController.navDelegate = self;
            infoNavController = [[UINavigationController alloc] initWithRootViewController:moreFromDeveloperCollectionViewController];
```

What I got in attach.
Have you got any suggestion?
![schermata 2015-02-13 alle 16 51 10](https://cloud.githubusercontent.com/assets/8709479/6190212/9773015a-b3a0-11e4-9d69-b519780afbfa.png)

**Comment by hons82** [comment]
Okay,
do u have added the dependencies ?
[dependecies](https://github.com/hons82/THMoreFromDeveloper/blob/master/THMoreFromDeveloper.podspec)

**Comment by foffux** [comment]
Yes, of course. I got them via cocoa pods installation.
I run "pod install" with Podfile:
...
pod 'THMoreFromDeveloper', '~> 0.0.1'
...
And what I got was:
...
Using Reachability (3.1.1)
Using SDWebImage (3.7.1)
Using THMoreFromDeveloper (0.0.2)
...
I also try with internet connection up. In fact, your project with storyboard loads angry birds app icons with no problems.

**Comment by hons82** [comment]
There was a Reachability issue with www.google.com
I changed to apple.com so now its working in my simulator

**Comment by foffux** [comment]
Unfortunately, this was not the issue for me. Nothing changed with apple.com.
In fact, I got the response from the web server, since I got the JSON response. Here you are a piece of this directly form Xcode output console:
Async JSON: {
    resultCount = 40;
    results =     (
                {
            artistId = 298910979;
....
I guess is something related to collection view, because the only difference from me and you is the storyboard that implements that.

**Comment by hons82** [comment]
It's probably because the IBOutlets in the "THMoreFromDeveloperCell.h" are not set without storyboard.
If I've more time next week I'll try to fix that.

**Comment by foffux** [comment]
Hello okay I see
Can yuo please let me know as soon as you will have fixed?
Or, you can explain me how to do that fix and will try by my self. It is
important for me to have this nice controller up and working.
Thank you

Il sabato 14 febbraio 2015, Hannes notifications@github.com ha scritto:

**Comment by hons82** [comment]
Actually there are 2 solutions that can work 4 you
1. Create a THMoreFromDeveloperCell.xib file define the Cell there and connect the IBoutlets there
2. Copy the Cell remove the IBoutlet and define the image and Label programmatically

These r quick fixes, until I've time to figure out how I can fix that

**Comment by foffux** [comment]
Hello.
Thanks for your quick answer, first of all.
If I could choose for one of the two fixes you were talking about, I would
pick the second one, since for my projects I was asked to not use interface
builder, if I could understand exactly your fixes.
Okay, I will wait for you since I know you can do what you told quite early.
Thank you very much, let me know if something changed.
Have a nice day.

2015-02-16 10:13 GMT+01:00 Hannes notifications@github.com:

**Comment by hons82** [comment]
I just made a commit (not yet on Cocoapods)
I would appreciate if you could just try to replace the THMoreFromDeveloperCell.h & .m in your sample project with those latest in the repo and test it for me.
Basically the initWithFrame seems to be called just when you don't use storyboard, and in this case the class provides a default implementation of the two fields. It may need more detail work to shape the cell nicely, however...

In my sample it seems to work...

**Comment by foffux** [comment]
Hello
I will do it as soon as possible, in some minutes and I will let you know.
Thank you.

2015-02-16 10:47 GMT+01:00 Hannes notifications@github.com:

**Comment by foffux** [comment]
Hello.
Good news. I think your fixes are good. What I can see is:

![schermata 2015-02-16 alle 11 21 51](https://cloud.githubusercontent.com/assets/8709479/6210264/2586bda4-b5ce-11e4-86b2-884a731e8510.png)

Just a couple of things to improve this fix:

1) You have to work on label displaying app names, because, as you can see from image I attached you, they are not well aligned.
2) Is it possible for you to provide also "emptyIcon" in resources folder in 3x version also for new iphone 6 plus?
3) I had a look at your fixes: just one doubt

``` objective-C
@property (strong, nonatomic) IBOutlet UILabel *appNameLabel;
@property (strong, nonatomic) IBOutlet UIImageView *appNameIcon;
```

I am not actual expert on IBOutlet but I have ever seen objects like that declared as weak. Is it okay for you to declare them as strong?

Thank you very much for this fix.

**Comment by hons82** [comment]
Great !!!
1. This is up to you... I create the image as a square on top of the cell and below the UILabel on the left bottom corner. So actually all you need to define is this method
   ´´´Objective-C
2. (CGSize)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout *)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath *)indexPath {
   CGSizeMake(128.0, 148.0);
   }
   ´´´
3. I'll try to add that soon
4. Generally IBOutlets are weak, so you don't need to release them on dealloc... but I can't assign something to a weak IBOutlet, that's why its strong now... Actually I've never had to create something for use in storyboard and without it... 
   so it should work (if I add a dealloc method to release it) but practically we'll need to try it :-)

~Hons

**Comment by foffux** [comment]
1) Yes you are right. There was my fault. I had to use 148.0f instead of 128.0f as I did. Now solved.
2) Ok great.
3) Perfect, understood. So in your new cocoa pods release, are you planning to include also a correspondent dealloc method for those strong IBOutlet, you are?

I will look forward for this new powerful release :-)
Thank you so much.

**Comment by hons82** [comment]
So... I made a couple of changes...
In my storyboard based apps its still working. 
Hope it works 4 u too

**Comment by foffux** [comment]
Do you want me to test them?
Maybe it is better and time saving...
Let me know.

2015-02-16 14:31 GMT+01:00 Hannes notifications@github.com:

**Comment by hons82** [comment]
If you have time...
I can't work anymore on it this week

**Comment by foffux** [comment]
Ok no problem for me.
Just give me new source files and I will test them.
Or have you already committed them on the repo?
Thank you.

2015-02-17 10:17 GMT+01:00 Hannes notifications@github.com:

**Comment by foffux** [comment]
Hello
I had a look at your latest changes and I think they are all right. At least, I can see the app icon in my project also with this controller version so I think it is good (even after new dealloc and draw methods
).
I just do not understand why you did:

``` objective-C
- (CGSize)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout *)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath *)indexPath {
    return (indexPath.row % 2 == 0 ? CGSizeMake(kCollectionWidthEven, kCollectionHeightEven) : CGSizeMake(kCollectionWidthOdd, kCollectionHeightOdd));
} 
```

Is there no a specific reason, right?
I also see you provide the 3x version of the emptyIcon image.
I tried to get your latest version with cocoa pods but I could not. With pod update/install I get version 0.0.2 and not 0.1.1.
I am using this line: pod 'THMoreFromDeveloper', '~> 0.0.1'. I think it is right.
Maybe not update yet?

Thank you.

**Comment by hons82** [comment]
Actually that piece of code is just to show how you can change the size of the collection item... It's just in the example program to show that... nothing else.

This `pod 'THMoreFromDeveloper', '~> 0.0.1'`means take "more or less" version 0.0.1. If you wanna take every new update just use `pod 'THMoreFromDeveloper'` or if you wanna stay on 0.1.x use it like this `pod 'THMoreFromDeveloper', '~> 0.1.0'` That's part of the cocoapods spec.

**Comment by foffux** [comment]
Hello
Ok I thought it was just an example, but I wanted to be 100% sure about that..
But with
pod 'THMoreFromDeveloper', '~> 0.0.1'
I thought I was able to catch every update >= 0.01, in fact I got 0.0.2 and I thought to be also able to get 0.1.x that it > 0.0.1. Probably I was wrong, so I used simply
pod 'THMoreFromDeveloper'

Thank you for the hint.
